# Generated by Django 6.0.3 on 2026-03-20 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('periods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('vacancies', models.IntegerField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantoes', to='periods.period')),
            ],
            options={
                'ordering': ['date', 'time_start'],
                'unique_together': {('period', 'date', 'time_start')},
            },
        ),
    ]
